# Copyright (C) 2025 BlueRock Security, Inc.
# All rights reserved.

import argparse
import runpy
import sys
import atexit
from . import backend
from . import installer
from . import cfg
from . import wrapper


def reload_unsafe_modules():
    # workaround for `from builtins import open as _builtin_open` in some standart libraries (bz2, tarfile, tokenize)

    unsafe_modules = ["bz2", "tokenize", "tarfile"]
    for mod in unsafe_modules:
        if sys.modules.get(mod) is not None:
            # we use del instead of importlib.reload() because reload
            # does not seem to work with some version of python (3.8 and Path.resolve)
            del sys.modules[mod]


def init_hooks():
    reload_unsafe_modules()

    if not cfg.config.oss:
        import bluepython.pickle_hooks  # noqa: F401
        import bluepython.pathtraversal_hooks  # noqa: F401
        import bluepython.process_hooks  # noqa: F401
        import bluepython.eval_hooks  # noqa: F401
        import bluepython.ctypes_hooks  # noqa: F401
        import bluepython.urllib_hooks  # noqa: F401
        import bluepython.aiohttp_hooks  # noqa: F401
        import bluepython.django_hooks  # noqa: F401
        import bluepython.sql_hooks  # noqa: F401
        import bluepython.flask_hooks  # noqa: F401
        import bluepython.archives_hooks  # noqa: F401
        import bluepython.symlink_hooks  # noqa: F401
        import bluepython.httpx_hooks  # noqa: F401
        import bluepython.uvicorn_hooks  # noqa: F401
        import bluepython.a2a_hooks  # noqa: F401
        import bluepython.crewai_hooks  # noqa: F401
        import bluepython.gemini_hooks  # noqa: F401
        import bluepython.openai_hooks  # noqa: F401
        import bluepython.opentelemetry_hooks  # noqa: F401
        import bluepython.anthropic_hooks  # noqa: F401
        import bluepython.litellm_client_hooks  # noqa: F401
        import bluepython.langchain_hooks  # noqa: F401

    import bluepython.mcp_hooks  # noqa: F401

    # should be the last to reduce noise generated by imports of previous hooks
    import bluepython.import_hooks  # noqa: F401

    if not cfg.config.oss:
        import bluepython.marshal_hooks  # noqa: F401

        # Enable tracing last since we do not want to trace our own modules.
        import bluepython.tracing

        bluepython.tracing.activate()


class BluePythonFinalizer:
    # hold a reference to backend and measurement to make sure it's not garbage collected
    # before dumping profiling data
    def __init__(self, be, cumulative):
        self._backend = be
        self._cumulative = cumulative
        atexit.register(self.finalize)

    def finalize(self):
        # Use the stored references
        wrapper.dump_profiling_data(self._cumulative, self._backend)


def init():
    # Set up acousticBackend at most once.
    if not backend.acousticBackend:
        backend.acousticBackend = backend.AcousticBackend()
        # backend has loaded sensor_config
        backend.debugLogging.enable = cfg.sensor_config.debug
        if cfg.sensor_config.profiling:
            BluePythonFinalizer(backend.acousticBackend, wrapper.Cumulative)
        backend.debug(f"Config: {cfg.config}")
        if cfg.sensor_config.log_stderr:
            backend.acousticBackend.tracing_stderr()
        if cfg.sensor_config.log_file:
            backend.acousticBackend.tracing_file(cfg.sensor_config.log_file)


# Memorizeses whether auto_setup() has already been called.
# When this is true, auto_setup() becomes a no-op (unless force is set).
# This is necessary because startup code may call auto_setup() multiple times.
# For example, this can happen if a .pth file that calls auto_setup() is found both through lib/
# and through lib64/ (in particular, if one of these directories is a symlink to the other).
auto_setup_done = False


def auto_setup(*, cfg_path=None, force=False):
    global auto_setup_done

    if auto_setup_done and not force:
        return

    try:
        cfg.load_cfg(cfg_path)
        if not cfg.config.instrumentation:
            return

        init()
        init_hooks()
    except Exception as e:
        # Python will ignore exceptions in .pth files.
        # To ensure that this does not cause the sensor to be accidentally disabled,
        # we kill the process with SIGKILL.
        print("bluepython: failed auto setup due to exception:", file=sys.stderr)
        import signal
        import traceback

        traceback.print_exception(e)
        signal.raise_signal(signal.SIGKILL)

    auto_setup_done = True


def main():
    # Minimum supported interpreter is Python 3.10. wrapt and
    # sys.addaudithook have worked since 3.8, but the MCP hooks
    # require 3.10+ (mcp and fastmcp package minimums), and several
    # type annotations in this module rely on 3.10+ syntax.
    if sys.version_info < (3, 10):
        print("bluepython: python >= 3.10 is required. Aborting.", file=sys.stderr)
        sys.exit(1)

    parser = argparse.ArgumentParser(prog="python3 -m bluepython")
    parser.add_argument("path", nargs="?", help="Python script to run (unless -m is given)")
    parser.add_argument("args", nargs=argparse.REMAINDER, metavar="...", help="Additional arguments")
    parser.add_argument("-m", dest="module", help="Execute Python module instead of file")
    parser.add_argument("-p", "--path-traversal", action="store_true", help="Pathtraversal events")
    install_group = parser.add_mutually_exclusive_group()
    install_group.add_argument("--install", action="store_true", help="Install BRU Python sensor autostart")
    install_group.add_argument("--uninstall", action="store_true", help="Uninstall BRU Python sensor")
    cfg.add_config_args(parser)

    args = parser.parse_args()

    if args.install:
        installer.install()
        return
    elif args.uninstall:
        installer.uninstall()
        return

    cfg.load_cfg_from_args(args)

    init()
    init_hooks()

    if args.module is not None:
        # We are running a Python module.
        # Note: the first component of sys.argv will be replaced by runpy.
        sys.argv = [""] + args.args
        runpy.run_module(args.module, run_name="__main__", alter_sys=True)
    elif args.path is not None:
        # We are running a Python script (by path).
        sys.argv = [args.path] + args.args
        runpy.run_path(args.path, run_name="__main__")
    else:
        print("bluepython: either -m or a path is required", file=sys.stderr)
        sys.exit(1)
